ALTER TABLE public."organizations" DROP COLUMN;
ALTER TABLE public."organizations" DROP COLUMN;
ALTER TABLE public."organizations" DROP COLUMN;
ALTER TABLE public."organizations" DROP COLUMN;
ALTER TABLE public."organizations" DROP COLUMN;
ALTER TABLE public."organizations" DROP COLUMN;
ALTER TABLE public."organizations" DROP COLUMN;
ALTER TABLE public."organizations" DROP COLUMN;
ALTER TABLE public."organizations" DROP COLUMN;