ALTER TABLE public."organizationCaches" DROP COLUMN;
ALTER TABLE public."organizationCaches" DROP COLUMN;
ALTER TABLE public."organizationCaches" DROP COLUMN;
ALTER TABLE public."organizationCaches" DROP COLUMN;
ALTER TABLE public."organizationCaches" DROP COLUMN;
ALTER TABLE public."organizationCaches" DROP COLUMN;
ALTER TABLE public."organizationCaches" DROP COLUMN;
ALTER TABLE public."organizationCaches" DROP COLUMN;
ALTER TABLE public."organizationCaches" DROP COLUMN;